### ISSUE TITLE
er.email :q这文件是错误生成的吗？

### ISSUE THREAD

**Issue by githubhao0705** [ProjectSky/FrackinUniverse-sChinese-Project#126]
我这边pull时，提示
error: unable to create file re.email q (Invalid argument) 
没法创建。

**Comment by githubhao0705** [comment]
三天前，Version: 5.3.8.4 automatic update done 内出现的。

**Comment by ProjectSky** [comment]
* Fix https://github.com/ProjectSky/FrackinUniverse-sChinese-Project/commit/91e0d172ca92429754b171c0a9e525f4542e1a32
