### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by githubhao0705** [ProjectSky/FrackinUniverse-sChinese-Project#2]
修改的文件提交到了吗?

**Comment by ProjectSky** [comment]
没有，差异0，提交0。

**Comment by ProjectSky** [comment]
刚新建了DEV分支，你可以先把文件提交进DEV分支里。

**Comment by githubhao0705** [comment]
这次我是直接上传的文件,而不是通过本地客户端github操作上传的,上一次或许是被墙的原因导致失败

**Comment by githubhao0705** [comment]
不过我选错了,我应该选DEV的

**Comment by ProjectSky** [comment]
重新pull一次。另外飞螳属于已确认的名词，就不要再改了。

**Comment by githubhao0705** [comment]
关于飞螳这个用词,我也是觉得别人说得很对,所以才特意改的,至于确认这一说,只是流传下来的汉化文字罢了,我不觉得有什么关系,如果单单看汉语,飞螳丝和异龙丝都很难表达出其中的生物样式,不过至少词源来自于sc,那么至少还有迹可循,而不可随意捏造

**Comment by githubhao0705** [comment]
我在试一个新的本地git客户端,稍等先

**Comment by githubhao0705** [comment]
我在试一个新的本地git客户端,稍等先

**Comment by githubhao0705** [comment]
嗯?SC里面mutalisk 是异龙,而SB里面则是mutavisk,所以得重新找来源了,等我忙完再慢慢追溯词意,看能否找到词源

**Comment by ProjectSky** [comment]
下次更新请Pull至DEV分支，主分支仅用做合并。

**Comment by githubhao0705** [comment]
嗯,已经修改为提交到DEV分支,还有飞螳就保留好了,实在找不到与之相关的词源

**Comment by githubhao0705** [comment]
http://www.xxximagetpb.org/images/2017/01/18/21321321421421.png
没有导出

**Comment by ProjectSky** [comment]
所有patch文件都是补丁，补丁文件不会做二次导出，且不能在补丁文件上再打补丁。
**解决方法**：可将源文件翻译后按层级提交进others目录用作覆盖。源文件不需要添加Chs标签，直接在原文上翻译即可。
**注意**：因为ptach属于MOD本体，所以others目录下的文件不做任何内容更新和校对。

**Comment by ProjectSky** [comment]
@githubhao0705 

* **注意chs标签对齐**（正确的格式是6个空格，而不是1个tab+2个空格）。
* 校对操作时这些chs不对齐的文件将被重新写入导致文件变化。
* 差异示例：
``` json
	  "Chs": "这是1个tab+2个空格",
      "Eng": "这是6个空格"
```
