### ISSUE TITLE
同名文件问题

### ISSUE THREAD

**Issue by ReIzay** [ProjectSky/FrackinUniverse-sChinese-Project#200]
FrackinUniverse-sChinese-Project/translations/texts/monsters/skills/ranged/ 目录下有：
shared_Attack.monsterskill.json   和
shared_attack.monsterskill.json

两个同名文件，每次clone，Repositories下来就会导致旧文件默认覆盖新文件

**Comment by ProjectSky** [comment]
Fix https://github.com/ProjectSky/FrackinUniverse-sChinese-Project/commit/b5caba47568098167ef7fed8ca76615aea321959
