### ISSUE TITLE
关于Frackin Races的汉化

### ISSUE THREAD

**Issue by DragonKnightOfBreeze** [ProjectSky/FrackinUniverse-sChinese-Project#306]
很久没有关注过FU的汉化了，主要是现在工作了，兴趣也从StarBound转向了Stellaris，以后可能还会回来重温StarBound的乐趣吧。
据说Frackin Races现在已经和FrackinUniverse合并了，不知道大家是如何处理Frackin Races的汉化的？
我的项目[FrackinRaces-sChinese-Project](https://github.com/DragonKnightOfBreeze/FrackinRaces-sChinese-Project)中有原FR的汉化文本，translations目录下，yaml格式，不知道大家之前是否曾经参考过这里的文本？之后有没有必要参考？
如果已经妥善汉化了FR的相关文本，那么我就将这个项目存档。

**Comment by ProjectSky** [comment]
这时候需要@diskrubbish
#297

**Comment by DragonKnightOfBreeze** [comment]
@ProjectSky 我一直很好奇为什么不直接使用yaml进行汉化呢？json某些时候真的挺不方便的。

**Comment by ProjectSky** [comment]
> 我一直很好奇为什么不直接使用yaml进行汉化呢？json某些时候真的挺不方便的。

因为这项目我已经很久没管理更新过了，基本处于半废弃的状态，但是FU又一直在更新，只能维护其自动化更新流程。

**Comment by DragonKnightOfBreeze** [comment]
py应该也有yaml插件的，直接把translations目录下的json文件全部转化成yaml文件并存储到另一个目录中，并不是什么难事

**Comment by DragonKnightOfBreeze** [comment]
但是。。。哎，很多时候就是没有什么干净，不愿意敲代码

**Comment by ProjectSky** [comment]
> 但是。。。哎，很多时候就是没有什么干净，不愿意敲代码

是的，主要还是兴趣问题，失去兴趣后就没什么动力再去干了

**Comment by DragonKnightOfBreeze** [comment]
干劲

**Comment by diskrubbish** [comment]
@DragonKnightOfBreeze Fr汉化的文本已经合并进Fu了，只可惜全部木大·，几次大改过后也不剩什么了。
yaml我在学，感觉和json比各有优缺点，具体采用哪种格式我觉得还要再考虑一下，
最后就是谢谢先辈的脚本，没这个stb汉化就是地狱

**Comment by DragonKnightOfBreeze** [comment]
@ProjectSky @diskrubbish 使用yaml替代json，其实只要写一个py脚本，导入yaml库和json库，然后新建一个translations_yaml目录，walk translations目录中的所有json文件到translations_yaml目录下就可以了，如果有必要的话，还可以重新从yaml导回json就可以了。不过。。。说起来简单，实际上starbound的json不是标准的json（允许注释和多行字符串），这方面要做特殊处理，有些麻烦

**Comment by DragonKnightOfBreeze** [comment]
@diskrubbish 脚本是sky写的，现在我基本看不懂py脚本了，个人实在不喜欢

**Comment by DragonKnightOfBreeze** [comment]
@ProjectSky @diskrubbish 周末重温了一下fu，感觉有些地方的文本还可以完善一下，目前有几种想法：
1. 编写json schema用于约束json文件，提供代码补全，如patch文件只允许op、path、value并限定类型（如字符串），这个功能搭配IDEA比较好，VSCode的话有些问题的，不适合中文路径和相对路径

**Comment by DragonKnightOfBreeze** [comment]
@ProjectSky @diskrubbish 
2. 编写一个简单的Idea插件，支持starbound富文本，主要就是颜色标签，另外可能还有一些特殊语法，如果使用Idea的话，我们可以让json schema规则指定一个字符串属性的语言注入，注入为starbound富文本，比如Chs和Eng这两个属性，就可以这样做，避免出现眼花的情况.不过这个也是搭配IDEA使用比较好。。。

**Comment by DragonKnightOfBreeze** [comment]
@ProjectSky @diskrubbish 一些特殊名词还是可以统一替换一下的，比如“夜族”和“夜种”这个还是统一一下比较好，还有“钢铁战刃”，可能我这样翻译给不少人带来了困惑。。。

**Comment by diskrubbish** [comment]
@DragonKnightOfBreeze 我这两天用下来还是使用json格式比较好，yml存在转储慢和上手很慢的两个问题，对其他人非常不友好
统一翻译的问题我会逐步解决，fu翻译真的很恼人
