### ISSUE TITLE
为什么研究科技树的文件不见了?

### ISSUE THREAD

**Issue by lsby** [ProjectSky/FrackinUniverse-sChinese-Project#320]
在`translations\texts\zb\researchTree`下

在6.0.1的时候还有这些`fu`开头的文件
![image](https://user-images.githubusercontent.com/7814085/95193861-12e93a00-0807-11eb-8070-7ec1aad25dcd.png)

但在6.0.11就不见了?
![image](https://user-images.githubusercontent.com/7814085/95193840-0b299580-0807-11eb-847d-a3b5da4ef105.png)

合并树是这样的
![image](https://user-images.githubusercontent.com/7814085/95194042-5f347a00-0807-11eb-980e-5dae7717eb3f.png)

**Comment by ProjectSky** [comment]
fix 3406e271218ba581851fe3548b30d877caa90ca7
