### ISSUE TITLE
idea的starbound text插件在哪里下载

### ISSUE THREAD

**Issue by ChenJunsen** [ProjectSky/FrackinUniverse-sChinese-Project#376]
idea内置的插件市场没有找到这款插件

**Comment by ProjectSky** [comment]
* https://plugins.jetbrains.com/plugin/15066-starbound-text 已被作者删除

@DragonKnightOfBreeze

**Comment by ChenJunsen** [comment]
申请加到协作者哇，https://github.com/ChenJunsen 1534717040@qq.com

**Comment by ChenJunsen** [comment]
> * https://plugins.jetbrains.com/plugin/15066-starbound-text 已被作者删除
> 
> @DragonKnightOfBreeze
申请加到协作者哇，https://github.com/ChenJunsen 1534717040@qq.com

**Comment by DragonKnightOfBreeze** [comment]
重新上传了，名字是Starbound Text，jetbrains正在审批，之前的似乎一直都没有审批。感觉没有太大用。。。大部分特殊格式的标记文本都是写在json字符串中的，太长的标记文本如果高亮了之后，编辑时会很卡（虽然颜色高亮看起来可能很好看）

**Comment by DragonKnightOfBreeze** [comment]
附件是插件jar包的压缩包   解压后使用idea从本地安装即可 [Starbound-Text-3.1.0.jar.zip](https://github.com/ProjectSky/FrackinUniverse-sChinese-Project/files/7580071/Starbound-Text-3.1.0.jar.zip)
