### ISSUE TITLE
种族选择旧翻译过时

### ISSUE THREAD

**Issue by THETATATA** [ProjectSky/FrackinUniverse-sChinese-Project#438]
我看到种族选择有新的未翻译也就算了

但是旧的翻译因为古早时期已经翻译过了，更新之后有了新文本但依旧被覆盖掉，真的没问题嘛？那个羽族的文本问题应该挺久了，哪里有入口可以进去重新翻译一下？

**Comment by ProjectSky** [comment]
请指出具体被覆盖的文本，如果每次更新都被覆盖，那这些文本很可能位于others中

**Comment by diskrubbish** [comment]
> 我看到种族选择有新的未翻译也就算了
> 
> 但是旧的翻译因为古早时期已经翻译过了，更新之后有了新文本但依旧被覆盖掉，真的没问题嘛？那个羽族的文本问题应该挺久了，哪里有入口可以进去重新翻译一下？

绝大部分的种族文本存于patch中，因为patch文件的特殊性，所以基本上都是我手动过滤再push上来的，羽族的话没记错已经没有了，貌似是fu放弃了对羽族的兼容...
如果还再使用fr汉化的话，请取消订阅，那已经是过时近四年的玩意了。

**Comment by THETATATA** [comment]
噢……我看到了，是avali的汉化MOD覆盖掉了FU的内容，在这里都还没翻译…突然就觉得好痛苦，SB社区的翻译大范围停滞了。
创意工坊的那个汉化我从合集里面还能看到，但是目前也已经转投github上面的了。
好吧，所以是因为别的汉化覆盖了才有这种问题，没事了。。。
